### ISSUE TITLE
Per endpoint http auth

### ISSUE THREAD

**Issue by ukd1** [sdogruyol/kemal#101]
Hey @sdogruyol, I took your middleware for http auth and made it so it works per request...

https://github.com/ukd1/plusone/blob/master/src/plusone/authed.cr

My version is kinda shitty, I'd like to get it up to scratch to add to kemal itself.

1. would you accept a pr?
2. what would you like changed (apart from adding specs, which I will of course)?

**Comment by sdogruyol** [comment]
@ukd1 i'm actually thinking of customizing the `http_basic_auth` middleware so that it'd both work for all endpoints / per endpoint.

The current one handles all endpoints with same username, password. Ideally for each different endpoint we need to register different username, password and need to match those. I think that could be done in a simple key, value based `Hash`.

WDYT?

**Comment by ukd1** [comment]
@sdogruyol yeah, this would be best - I could do that with your existing code by splitting it up a bit so that it could be called stand-alone. Thoughts?

**Comment by sdogruyol** [comment]
Sure. That's also what i thought :+1:
