### ISSUE TITLE
port ?  ecr include ?

### ISSUE THREAD

**Issue by tigernassau** [sdogruyol/kemal#186]
nice framework 
minor isssues and maybe crystal issues but we cant' find anywhere: 
1) how can we change to start on another port ?  ie 8000 instead of 3000
2) how can we include other ecr files ie. 
home.ecr:
<%- include header.ecr %>
<%- include footer.ecr %>
this syntax gave errors
thks

**Comment by Angarsk8** [comment]
Hi @tigernassau , 

For running  a `Kemal` project on another port different to 3000, you have two alternatives (or even more):

1.  You can compile the app by executing the command `crystal build src/<name_of_your_app>.cr [options]`, execute the command `./<name_of_your_app> --port <port_number>` and your app will run in the specified port if it is available.

2.  You can change the default configuration used by Kemal to run the server in development mode. To do that you have to go to `libs/kemal/kemal/config.cr` and change the instance variable of the class `Config` at the line `19`, in order to run the app in the desired port.

I think it would be nice if Kemal used a config file to write this kind of settings.

**Comment by sdogruyol** [comment]
You can change environment with `KEMAL_ENV`.

**Comment by plainas** [comment]
Can you guys add this to the documentation on kemal's website?

**Comment by sdogruyol** [comment]
@plainas just opened an issue on kemalcr.com repo 👍

**Comment by oltmannsdaniel** [comment]
@sdogruyol But how does the ECR include stuff works?

So include a view partial from another folder?

**Comment by sdogruyol** [comment]
@oltmannsdaniel you can use `render` inside you `ecr` file.

```erb
# /views/main.ecr
<%= render "./views/partial.ecr" %>

Hello from main.
```
