### ISSUE TITLE
Serving JSON doesn't work

### ISSUE THREAD

**Issue by asterite** [sdogruyol/kemal#211]
I run the example [here](http://kemalcr.com/docs/json/)

``` cr
require "kemal"
require "json"

get "/" do |env|
  env.response.content_type = "application/json"
  {name: "Serdar", age: 27}
end

Kemal.run
```

Doing a request I get:

```
{name: "Serdar", age: 27}
```

which is not a JSON. It seems `to_s` is always invoked on the returned object, and in fact I can't find a `to_json` method call in kemal's source code...

**Comment by sdogruyol** [comment]
Hey @asterite, thanks for the report. Actually you are right. The examples are not correct and this is not a valid JSON response.

I'll update the docs as required 👍

**Comment by sdogruyol** [comment]
On second thought. Instead of calling `to_s` on everything i could've just call `to_json` if the content-type is `application_json`. WDYT?

**Comment by asterite** [comment]
@sdogruyol Yes, I thought kemal did that: if the content type is `application/json` then invoke `to_json` instead of `to_s`. I think the example in the docs was explaining that :-)

**Comment by asterite** [comment]
But I don't know, it can be unintuitive... if you invoke `to_json(response)` and the content type is set, what will happen next? Maybe this needs a bit more discussion.

**Comment by sdogruyol** [comment]
I think it's OK. Could you please take a look at https://github.com/sdogruyol/kemal/pull/212

**Comment by f** [comment]
What about making object responses convert to json automatically?

If user wants an object to be returned from an endpoint, they probably want
JSON.

> --

*Fatih Kadir Akın*http://github.com/f
http://twitter.com/fkadev

**Comment by jaitaiwan** [comment]
I agree with @f and I think that this is fairly intuitive and OK if you have it documented. I think a few other frameworks like expressjs do this as well (documented) and its quite a time saving feature. LGTM?

**Comment by sdogruyol** [comment]
@f https://github.com/sdogruyol/kemal/pull/212 does that. Mind taking a look?

**Comment by bcardiff** [comment]
I would suggest something more declarative rather than reading the header. 

There might be another headers that would benefit from json conversion. For example if you want to return geojson `application/vnd.geo+json` or ldjson `application/ld+json`. 

Or we could go sadly on a situation where we need to tweak the header [like in IE7](http://www.entwicklungsgedanken.de/2008/06/06/problems-with-internet-explorer-and-applicationjson/) .

Having a `render_json(object)` method that will set a header (if none is set) and encoding to json seems a cleaner to me. Or eventually a `render json: object` api could appear.

**Comment by jwoertink** [comment]
Just to jump in on this, my thought is that setting the return type should be declarative. Making assumptions on the return type is really nice; however, that starts to make things a bit more like a "framework". There should be a way to set a global value for what your app is doing, as well as a way to override locally.

```ruby
require "kemal"

Kemal.config.respond_as = :json

get "/" do
   {name: "Jeremy"} # responds to content type application/json with valid JSON {"name": "Jeremy"}
end

get "not_json" do |env|
  env.respond_as = :text
  "This is not json" # responds to content type text/plain with the text "This is not json"
end
```

By adding a simple config like this, we don't have to worry about setting the content type per route. Also, this could make it easy to add in content types like `geo+json`, `ld+json`, xml, pdf or whatever you want with something like `:geo_json`, `:ld_json`, `:xml`, etc... And then if no setting is set, we just default it to HTML.

**Comment by jaitaiwan** [comment]
I think these are good comments, especially regarding multiple mime types requiring JSON encoding.
A thought I just had is that because any forward solution is likely to be fairly declarative, the way in which it is implemented probably needs to be done such that implementers can easily wrap the method [get, post, ...] calls in their own function to automate an endpoint being json or xml etc. Implementers aren't going to want to write env.return_type = :json every time they want a JSON endpoint if it's a json API.






On Wed, Sep 28, 2016 at 3:07 AM +1000, "Jeremy Woertink" <notifications@github.com> wrote:












Just to jump in on this, my thought is that setting the return type should be declarative. Making assumptions on the return type is really nice; however, that starts to make things a bit more like a "framework". There should be a way to set a global value for what your app is doing, as well as a way to override locally.

require "kemal"

Kemal.config.respond_as = :json

get "/" do
   {name: "Jeremy"} # responds to content type application/json with valid JSON {"name": "Jeremy"}
end

get "not_json" do |env|
  env.respond_as = :text
  "This is not json" # responds to content type text/plain with the text "This is not json"
end



By adding a simple config like this, we don't have to worry about setting the content type per route. Also, this could make it easy to add in content types like geo+json, ld+json, xml, pdf or whatever you want with something like :geo_json, :ld_json, :xml, etc... And then if no setting is set, we just default it to HTML.

**Comment by sdogruyol** [comment]
For now i've updated the docs to explicitly use `to_json` http://kemalcr.com/docs/json

**Comment by crisward** [comment]
I don't mind the `to_json` as its more declarative. 
But I'd like kemal to set the `content_type = "application/json"` if content_type hasn't already been set. Having to add that to every route is a bit ugly, but the `to_json` is fine. Not sure how easy it is to detect a string as being json.

**Comment by etemelkuran** [comment]
if response type is declared as json, it should return json. extra arguments doesnt make sense.

**Comment by sdogruyol** [comment]
Closing this for now.
