### ISSUE TITLE
CORS headers for static assets

### ISSUE THREAD

**Issue by omarroth** [sdogruyol/kemal#228]
Hi, I'm having trouble adding headers to files served by Kemal.
Doing
~~~crystal
before_all do |env|
  env.response.headers.add "Access-Control-Allow-Origin", "*"
end
~~~
does not appear to do anything on static files, and adding a custom handler such as
~~~crystal
class CORSHandler < HTTP::Handler
  def call(context)
    context.response.headers.add "Access-Control-Allow-Origin", "*"
    call_next context
  end
end
~~~
also does nothing.

**Comment by sdogruyol** [comment]
Unfortunately this won't work on public files.

**Comment by omarroth** [comment]
Fair enough.
A quick fix I found would be
```diff
diff --git a/src/kemal/static_file_handler.cr b/src/kemal/static_file_handler.cr
index 4e26d51..23d9bbd 100644
--- a/src/kemal/static_file_handler.cr
+++ b/src/kemal/static_file_handler.cr
@@ -52,6 +52,7 @@ module Kemal
       elsif File.exists?(file_path)
         return if self.etag(context, file_path)
         minsize = 860 # http://webmasters.stackexchange.com/questions/31750/what-is-recommended-minimum-object-size-for-gzip-performance-benefits ??
+        context.response.headers.add("Access-Control-Allow-Origin", "*")
         context.response.content_type = mime_type(file_path)
         request_headers = context.request.headers
         filesize = File.size(file_path)
```
which works well enough for me.

**Comment by MGerrior** [comment]
@sdogruyol What do you think about removing the static file handler from the initial set-up and allowing users to add it manually, thus providing more customization options? I've been toying with the idea in [this commit](https://github.com/MGerrior/kemal/commit/0d43c7161a1ecea6b174c39a559c956b9d2978ea) but it's not ready for a PR. This would allow removing the `serve_static` hash/boolean, and provide users the ability to customize the handler before adding it to the stack, enabling things like this:

```crystal
require "kemal"

# Matches GET "http://host:port/"
get "/" do
  "Hello World!"
end

static_file_handler = Kemal::StaticFileHandler.new("./public")
static_file_handler.set_headers do |response, path|
  if path =~ /\/assets\//
    response.headers.add("Access-Control-Allow-Origin", "*")
  end
end

Kemal.run
```

I'm basing the method signature off of the signature used in the `express.js` static file middleware as seen [here](https://expressjs.com/en/4x/api.html#express.static).

It could also allow for more advanced customization options via a hash as the second argument to `new` instead of just the boolean value for `passthrough`.

**Comment by sdogruyol** [comment]
@MGerrior that sounds interesting. I have to give it a thought.

**Comment by sdogruyol** [comment]
@MGerrior can you open a different issue for this?

**Comment by MGerrior** [comment]
Sure thing @sdogruyol , opened as a new issue, #233 and refactored a little bit (though still not PR ready, unless you want the diff to make it easier).

**Comment by rdp** [comment]
Thanks for posting this, it gave me great instructions on how to enable it for dynamic content, which is what I needed at the time :)

**Comment by omarroth** [comment]
@rdp Glad it helped.
I think I will close this, as extending the StaticFileHandler rather than modifying it is a more robust solution.
Superseded by #233.
