### ISSUE TITLE
Route not matching for paths that start the same but differ at a url param

### ISSUE THREAD

**Issue by samueleaton** [sdogruyol/kemal#230]
Both of these paths should return the values for `:x` and `:y` respectively but they both return a 404 response:

```ruby
get "cat/:x" do |env|
  env.response.content_type = "text/plain"
  env.params.url["x"]
end

get "cat/:y/meow" do |env|
  env.response.content_type = "text/plain"
  env.params.url["y"]
end
```

If I were to change the spelling of one of the paths to be `cats` but keep the other as `cat` then they both work. Also, if I were to change the url params to be the same values (e.g. if both were `:x`) then they would both work.

It doesn't matter the length of the paths or url params. For example, the following would also NOT work:

```ruby
get "user/account/:email" do |env|
  env.response.content_type = "text/plain"
  env.params.url["email"]
end

get "user/account/:account_id/info" do |env|
  env.response.content_type = "text/plain"
  env.params.url["account_id"]
end
```
Again if one of the paths changed or if the url params were identical, then the paths work.

The following DOES work (because `user` is spelled differently in each route):

```ruby
get "users/account/:email" do |env|
  env.response.content_type = "text/plain"
  env.params.url["email"]
end

get "user/account/:account_id/info" do |env|
  env.response.content_type = "text/plain"
  env.params.url["account_id"]
end
```

The following DOES work (because they have the same url params):

```ruby
get "user/account/:account_id" do |env|
  env.response.content_type = "text/plain"
  env.params.url["email"]
end

get "user/account/:account_id/info" do |env|
  env.response.content_type = "text/plain"
  env.params.url["account_id"]
end
```

**Comment by sdogruyol** [comment]
Unfortunately, this is a limit of the current Radix implementation. See https://github.com/luislavena/radix#caveats

**Comment by sdogruyol** [comment]
Ping @luislavena

**Comment by luislavena** [comment]
@samueleaton as pointed out by @sdogruyol, you can workaround the Radix limitation by some tweaks in the pattern being used.

The radix implementation is fast because it avoids look-ahead searches that will be necessary to distinguish different URLs, but not only that, it might make the implementation code more complicated and potentially slower.

There are more details on this on luislavena/radix#5

@sdogruyol it seems Kemal references an old version of Radix (not even the deprecation warning). I recommend updating to latest so the exception described in the README is returned to the user.

Cheers.

**Comment by sdogruyol** [comment]
@luislavena Kemal references to Radix `v0.3.1`. Isn't that the latest release?

**Comment by luislavena** [comment]
@sdogruyol sorry, my bad, seems that was upgraded a few versions ago (it was stuck on my brain by the time I fixed that issue).

It should be good now :smile:

**Comment by luislavena** [comment]
Said it referenced an old version because attempt to add two paths to the same tree with mismatching keys should have raised `Radix::SharedKeyError` exception. Only old versions of Radix didn't raise and could have been the reason of this report.

**Comment by samueleaton** [comment]
> it might make the implementation code more complicated and potentially slower

I think whether or not it functions is more important than speed. Lots of things could be faster if you don't care if they work or not. 

I'm trying to port an existing API to crystal/kemal but I'm not able to preserve the route names because I get a 404 in Kemal. There are things in production relying on my APIs so unfortunately changing the path names is not an option. 😞

As it stands, Kemal is unusable for my project until the routing works for any path. I'd be willing to help any way I can.

**Comment by luislavena** [comment]
> I think whether or not it functions is more important than speed. Lots of things could be faster if you don't care if they work or not.

I beg to differ, speed is as important as correctness. Not only runtime speed but also onboarding/readability.

Radix was extracted from our routing library that we use with 280+ endpoints without issues. This was a port from our Rails application and encountered no issues during the process.
 
It was inspired and implemented following other Radix implementations, which also suffer the same caveats (some might advertise it as *feature* :grin:)

I assume the issue is naming the parameter `:email_or_account_id` (or something like that?)

It might be possible introduce the lookahead code required for this, but I had not encountered that need and from my initial exploration when looking at the report linked before, it might impact code readability and speed (considerably)

You're welcome to take a look at the source:

https://github.com/luislavena/radix

I believe implementation is well documented and test-covered, but feel free to ask any questions if you need further clarifications.

Cheers.

**Comment by samueleaton** [comment]
@luislavena I apologize. I was in a frustrated after a long day 😣  and didn't notice an unrelated reason for me getting a 404. My original post still stands but ignore my earlier comment from today. 😅

**Comment by luislavena** [comment]
@samueleaton I understand, thank you.

As I mentioned, we haven't encountered such need but that doesn't necessarily mean it might not exist for others.

If the issue is the following routes:

```crystal
get "user/account/:email" do |env|
  env.response.content_type = "text/plain"
  env.params.url["email"]
end

get "user/account/:account_id/info" do |env|
  env.response.content_type = "text/plain"
  env.params.url["account_id"]
end
```

My workaround recommendation would be adjust so both patterns use the same variable:

```crystal
get "user/account/:email_or_account_id"
get "user/account/:email_or_account_id/info"
```

And reference them as `env.params.url["email_or_account_id"]`. I know, is not pretty, but it might get the job done until a proper exploration of Radix lookahead is possible :smile: 

Cheers.

**Comment by shiba-hiro** [comment]
Hi, @sdogruyol
I'd like to suggest to keep this as a open issue.

Actually there is a workaround that @luislavena mentioned, and Radix still has limitation,
but I believe that current spec is not best as a web framework.

If there will be other better library for tree, we can replace Radix.
If Kemal can resolve a string which developers wrote to appicable one for Radix, we can fix it.

Users of web framework Kemal don't want to know how Kemal is implemented.
Users just want to express appropriate url for their products, which can make source code readable, can express the resource server manages.

What do you think?

**Comment by zbaylin** [comment]
I too suggest that this issue be reopened. Either that, or make sure that this is clearly documented somewhere. It's pretty common to address a resource using different methods, and this makes it impossible to do so in a clear manner.

**Comment by anykeyh** [comment]
Actually, if it cannot be fixed, it would be great to raise a runtime error on routes registration at least.

The current behavior is really bad and it confused me for a while until I read this issue.
