### ISSUE TITLE
kemal: 404 adopt string given :|

### ISSUE THREAD

**Issue by rdp** [sdogruyol/kemal#249]
It was a bit surprising that the default 404 handler "ignores" returned strings, ex:
```

get "/" do |env|
  env.response.status_code = 404
  "here is some failure text, unable to find something"
end

```

because by default kemal uses the return strings, but then for a "404" case it silently ignores it by default.  Might be nice to have the default 404 handler text somehow include any given text returned from the proc.

Cheers!

**Comment by sdogruyol** [comment]
Unfortunately you can't do this. Instead you can customize your 404 error.

```crystal
error 404 do |env|
  env.response.print "here is some failure text, unable to find something"
end
```

**Comment by rdp** [comment]
Right, I guess consider this a feature request that it can return more
easily custom strings to the 404.

**Comment by samueleaton** [comment]
would something like this work?

```ruby
get "/" do |env|
  env.response.status_code = 404
  env.response.print "here is some failure text, unable to find something"
  env.response.close
end
```

**Comment by KCErb** [comment]
@sdogruyol sorry if this is the wrong place, but I'm looking for something similar. For example, I would hope that something like this would work:

```crystal
error 404 do |env, err|
  env.response.content_type = "application/json"
  {message: err.message}.to_json
end

get "/thing/:id" do |env|
  # try to get id but it doesn't exist
  # ... omitted for brevity
  env.response.status_code = 404
  raise RouteNotFound("Thing not found for id: #{id}")
end
```

But instead, that error (and the others) does not accept my custom response content. So it seems I need to do something more manual like:

1. remove the existing 404 from handlers and return my own content as if it were a normal response (i.e. don't raise)
or
2. close the response before my route proc ends so that your tooling can't affect it?

Am I missing the right way to do this?

**Comment by KCErb** [comment]
Update, you can't really remove the existing 404 handlers. If you remove them before you call run, then run adds them back, if you clear them after, the config was already read so mutations don't do anything. :(

I guess I have to close the response?
