### ISSUE TITLE
kemal-jwt middleware 

### ISSUE THREAD

**Issue by qio-io** [sdogruyol/kemal#47]
Hello:

How can i approach the implementation of jwt in Kemal? When to enode the jwt token and how to verify the jwt signature and respond with 401 if is invalid?

The code in the below repository is a fork from one of the jwt ruby libraries.
https://github.com/Ravenstine/jwt.cr

**Comment by sdogruyol** [comment]
Hey there,

You can do this as a `middleware` like `kemal-pg` or `basic_auth`

I think [basic_auth](https://github.com/sdogruyol/kemal/blob/master/src/kemal/middleware/http_basic_auth.cr) will be a good guide for what you want to do.

**Comment by qio-io** [comment]
Thanks @sdogruyol ,

In `basic_auth` How do you enforce the authorized? method verification for some routes and for the others you let it pass through. Do you have an example of this middleware in use?

**Comment by sdogruyol** [comment]
Oh, that's not possible as of now. When you use `basic_auth` it applies to all routes :(

**Comment by qio-io** [comment]
Ok, thanks for the reply.

**Comment by vectorselector** [comment]
@sdogruyol 
would it be correct to use filters with "only" for specifying protected routes?

other (semi-related) question:  if implementing jwt storage on client cookie, would the kemal-csrf package be able to function without server-session context, but with stateless jwt?

thank you, and my apologies if it's incorrect to comment on closed issues,  or add additional related questions.

you will note a large interest in jwt auth workflows at this current time, due to it's statelessness and scalability versus server-sessions (fitting well with crystals single process model)
